version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: todo_list_mysql_1
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickylist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d

  php-apache:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql  # <--- IMPORTANT : doit être EXACTEMENT le nom du service MySQL ci-dessus
      PMA_PORT: 3306
    depends_on:
      - mysql

volumes:
  mysql-data:
  mongo-data:
