version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"  # Tu accèderas à ton site sur http://localhost:8080
    volumes:
      - .:/var/www/html  # Synchronise ton code local avec le conteneur
    depends_on:
      - mysql
      - mongo
    networks:
      - todo-network

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: tickylist
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - todo-network


  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

volumes:
  mysql-data:
  mongo-data:

networks:
  todo-network:
